version: '3.8'

services:
  # پایگاه داده PostgreSQL
  postgres:
    image: postgres:15
    container_name: personal_ai_postgres
    environment:
      POSTGRES_DB: personal_ai_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai_network

  # Redis برای کش و صف
  redis:
    image: redis:7-alpine
    container_name: personal_ai_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_network

  # برنامه اصلی
  app:
    build: .
    container_name: personal_ai_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/personal_ai_assistant
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - ./logs:/app/logs
    networks:
      - ai_network
    restart: unless-stopped

  # رابط کاربری React
  frontend:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    container_name: personal_ai_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - app
    networks:
      - ai_network
    restart: unless-stopped

  # Celery Worker برای کارهای پس‌زمینه
  celery_worker:
    build: .
    container_name: personal_ai_celery
    command: celery -A src.core.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/personal_ai_assistant
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - ai_network
    restart: unless-stopped

  # Celery Beat برای کارهای زمان‌بندی شده
  celery_beat:
    build: .
    container_name: personal_ai_beat
    command: celery -A src.core.celery beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/personal_ai_assistant
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - ai_network
    restart: unless-stopped

  # Nginx برای Load Balancing و Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: personal_ai_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
      - frontend
    networks:
      - ai_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ai_network:
    driver: bridge
